// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Capture run item with denormalized shader/scene info for API responses
 */
export type CaptureRunItemWithContext = { id: string, run_id: string, shader_version_id: string, scene_id: string, profile: string | null, status: string, capture_id: string | null, error_message: string | null, error_log: string | null, duration_ms: number | null, started_at: string | null, completed_at: string | null, shader_name: string, shader_slug: string, shader_version: string, scene_name: string, };
