// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureFreshness } from "./CaptureFreshness";
import type { CaptureWithContext } from "./CaptureWithContext";

/**
 * Full capture details for admin detail view, including technical metadata
 * and related captures for cross-referencing.
 */
export type CaptureDetail = { id: string, scene_id: string, shader_slug: string, shader_name: string, shader_version: string, shader_version_id: string, profile: string | null, image_path: string | null, image_url: string | null, thumbhash: string | null, captured_at: string | null, resolution_width: number | null, resolution_height: number | null, file_size_bytes: bigint | null, run_id: string | null, run_status: string | null, shader_author: string | null, scene_name: string | null, scene_slug: string | null, freshness: CaptureFreshness, status: string, error_message: string | null, video_url: string | null, avg_fps: number | null, min_fps: number | null, max_fps: number | null, frame_time_avg: number | null, frame_time_p99: number | null, minecraft_version: string | null, iris_version: string | null, gpu_model: string | null, content_type: string | null, world_version_id: string | null, scene_version_id: string | null, created_at: string, updated_at: string, same_shader_scene: Array<CaptureWithContext>, same_scene: Array<CaptureWithContext>, same_run: Array<CaptureWithContext>, };
