// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response with presigned URL for world upload
 */
export type CreateWorldUploadResponse = { upload_id: string, presigned_url: string, expires_at: string, };
