// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error response from POST /api/device/token (RFC 8628 error codes)
 */
export type DeviceTokenError = { error: string, error_description: string | null, };
