// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Successful response from POST /api/device/token
 */
export type DeviceTokenResponse = { access_token: string, token_type: string, 
/**
 * Seconds until token expires
 */
expires_in: bigint, };
