// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from GET /api/device/code/:user_code (for frontend to check code status)
 */
export type DeviceCodeStatus = { user_code: string, status: string, expires_at: string, };
