// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A before/after pair for the homepage hero slider.
 * Dynamically selected from popular shaders.
 */
export type FeaturedPair = { left_image_url: string, left_thumbhash: string | null, left_shader_name: string, left_scene_name: string, right_image_url: string, right_thumbhash: string | null, right_shader_name: string, right_scene_name: string, };
