// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SceneWithWorld = { world_name: string | null, world_slug: string | null, id: string, name: string, slug: string, description: string | null, world_id: string, x: number, y: number, z: number, pitch: number, yaw: number, dimension: string, time_of_day_ticks: number, weather: string, weather_intensity: number, moon_phase: number | null, biome: string | null, definition_json: string | null, active: boolean, created_at: string, };
