// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A specific revision of a Scene's config (position, camera, weather, etc.)
 */
export type SceneVersion = { id: string, scene_id: string, x: number, y: number, z: number, pitch: number, yaw: number, time_of_day_ticks: number, weather: string, weather_intensity: number, moon_phase: number | null, biome: string | null, created_at: string, };
