// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureWithContext } from "./CaptureWithContext";
import type { SceneVersion } from "./SceneVersion";
import type { World } from "./World";

export type SceneWithCaptures = { version: SceneVersion, world: World | null, captures: Array<CaptureWithContext>, id: string, name: string, slug: string, description: string | null, world_id: string, dimension: string, parent_scene_id: string | null, active: boolean, created_at: string, };
