// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionInfo = { token_prefix: string, created_at: string, expires_at: string, };
