// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureWithContext } from "./CaptureWithContext";
import type { ShaderVersionDetail } from "./ShaderVersionDetail";

export type ShaderWithCaptures = { versions: Array<ShaderVersionDetail>, captures: Array<CaptureWithContext>, id: string, name: string, slug: string, description: string | null, modrinth_id: string | null, curseforge_id: string | null, website_url: string | null, icon_url: string | null, source_url: string | null, license_id: string | null, upstream_downloads: bigint | null, upstream_updated_at: string | null, last_synced_at: string | null, created_at: string, updated_at: string, };
