// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shader author from upstream platform
 */
export type ShaderAuthor = { id: string, shader_id: string, name: string, url: string | null, platform: string, };
