// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Specific release of a shader pack
 */
export type ShaderVersion = { id: string, shader_id: string, version: string, modrinth_version_id: string | null, curseforge_file_id: number | null, download_url: string | null, file_hash: string | null, file_size: bigint | null, game_versions: string | null, release_channel: string | null, 
/**
 * JSON array of profile names, discovered after first capture
 */
supported_profiles: string | null, upstream_published_at: string | null, created_at: string, capture_failure_count: number, last_capture_error: string | null, };
