// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sort order for shader browsing (when no search query is provided)
 */
export type ShaderSearchSort = "popular" | "recent";
