// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";
import type { Feature } from "./Feature";
import type { ShaderAuthor } from "./ShaderAuthor";

export type ShaderListItem = { authors: Array<ShaderAuthor>, categories: Array<Category>, features: Array<Feature>, latest_version: string | null, game_versions: Array<string> | null, image_url: string | null, thumbhash: string | null, id: string, name: string, slug: string, description: string | null, modrinth_id: string | null, curseforge_id: string | null, website_url: string | null, icon_url: string | null, source_url: string | null, license_id: string | null, upstream_downloads: bigint | null, upstream_updated_at: string | null, last_synced_at: string | null, created_at: string, updated_at: string, };
