// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionInfo } from "./SessionInfo";

export type UserWithSessions = { sessions: Array<SessionInfo>, id: number, discord_id: string, discord_username: string, discord_avatar: string | null, role: string, created_at: string, updated_at: string, };
