// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single work item: one (shader_version, scene, profile) triple to capture
 */
export type WorkItem = { shader_version_id: string, shader_id: string, shader_slug: string, shader_name: string, version: string, download_url: string | null, file_hash: string | null, scene_id: string, scene_slug: string, scene_name: string, scene_dimension: string, scene_x: number, scene_y: number, scene_z: number, scene_yaw: number, scene_pitch: number, scene_time_of_day_ticks: number, scene_weather: string, scene_weather_intensity: number, scene_moon_phase: number | null, scene_biome: string | null, world_id: string, world_slug: string, world_name: string, world_file_url: string | null, world_file_hash: string | null, world_size_bytes: bigint | null, world_version_id: string | null, scene_version_id: string | null, profile: string | null, };
