// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single work item: one (shader_version, scene, profile) triple to capture
 */
export type WorkItem = { shader_version_id: string, shader_id: string, shader_slug: string, shader_name: string, version: string, download_url: string | null, file_hash: string | null, scene_id: string, scene_slug: string, scene_name: string, scene_definition_json: string, world_id: string, world_slug: string, world_name: string, world_file_url: string | null, world_file_hash: string | null, world_size_bytes: bigint | null, profile: string | null, };
