// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Downloadable world files containing scenes
 */
export type World = { id: string, slug: string, name: string, description: string | null, minecraft_version: string, file_url: string | null, file_hash: string | null, size_bytes: bigint | null, created_at: string, updated_at: string, };
