// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Preview thumbnail for a world (from its first available capture)
 */
export type WorldPreviewCapture = { image_url: string | null, thumbhash: string | null, };
