-- Add display_name column to shader_version_profiles.
--
-- Precomputed, normalized display name generated by Rust during extraction.
-- Empty string is a sentinel: the backfill service will recompute these.

ALTER TABLE shader_version_profiles
    ADD COLUMN display_name TEXT NOT NULL DEFAULT '';
