// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdoptPreviewAuthor } from "./AdoptPreviewAuthor";

/**
 * Preview response before confirming adoption
 */
export type AdoptPreviewResponse = { platform: string, name: string, slug: string, description: string, icon_url: string | null, downloads: number, version_count: number, authors: Array<AdoptPreviewAuthor>, };
