// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuditSummary = { total_r2_objects: number, total_r2_bytes: number, total_db_references: number, orphaned_count: number, orphaned_bytes: number, stale_staging_count: number, missing_count: number, unknown_prefix_count: number, url_mismatch_count: number, };
