// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single object found in R2 during audit
 */
export type AuditObject = { key: string, size: number, last_modified: string, 
/**
 * The R2 key prefix (e.g. "captures", "packages", "_uploads")
 */
prefix: string, };
