// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A DB row that references a missing or mismatched R2 object
 */
export type AuditReference = { table: string, row_id: string, stored_url: string, 
/**
 * For missing: same as stored_url. For mismatch: what the URL should be.
 */
expected_url: string | null, };
