// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackgroundId } from "./BackgroundId";
import type { ThemeMode } from "./ThemeMode";

/**
 * A page background image stored in R2.
 */
export type Background = { id: BackgroundId, image_url: string, image_path: string, thumbhash: string | null, theme_mode: ThemeMode, enabled: boolean, sort_order: number, original_filename: string | null, width: number | null, height: number | null, file_size_bytes: number | null, content_type: string | null, created_at: string, updated_at: string, };
