// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackgroundId } from "./BackgroundId";

/**
 * Response for initiating a background upload.
 */
export type BackgroundUploadResponse = { id: BackgroundId, presigned_url: string, image_url: string, image_path: string, };
