// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureHealthSummary } from "./CaptureHealthSummary";
import type { CaptureTargetHealth } from "./CaptureTargetHealth";

/**
 * Full capture health response
 */
export type CaptureHealthResponse = { targets: Array<CaptureTargetHealth>, summary: CaptureHealthSummary, };
