// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureId } from "./CaptureId";
import type { CaptureStatus } from "./CaptureStatus";
import type { SceneId } from "./SceneId";
import type { ShaderVersionId } from "./ShaderVersionId";

/**
 * Lightweight capture summary for public list endpoints.
 *
 * Omits performance metrics, GPU info, error details, and other fields
 * that are only needed on the detail view (`GET /api/captures/{id}`).
 */
export type CaptureListItem = { id: CaptureId, shader_version_id: ShaderVersionId, scene_id: SceneId, status: CaptureStatus, profile?: string, image_url?: string, thumbhash?: string, captured_at?: string, resolution_width?: number, resolution_height?: number, };
