// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DominantColor } from "./DominantColor";
import type { LuminanceData } from "./LuminanceData";

/**
 * Per-capture image analysis computed by the mod's CaptureAnalyzer.
 */
export type CaptureAnalysis = { luminance: LuminanceData, edge_density: number, dominant_colors: Array<DominantColor>, };
