// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureId } from "./CaptureId";
import type { CaptureStatus } from "./CaptureStatus";
import type { SceneId } from "./SceneId";
import type { SceneVersionId } from "./SceneVersionId";
import type { ShaderVersionId } from "./ShaderVersionId";
import type { WorldVersionId } from "./WorldVersionId";

export type Capture = { id: CaptureId, shader_version_id: ShaderVersionId, scene_id: SceneId, profile: string | null, image_url: string | null, image_path: string | null, video_url: string | null, avg_fps: number | null, min_fps: number | null, max_fps: number | null, frame_time_avg: number | null, frame_time_p99: number | null, minecraft_version: string | null, iris_version: string | null, gpu_model: string | null, resolution_width: number | null, resolution_height: number | null, captured_at: string | null, status: CaptureStatus, error_message: string | null, thumbhash: string | null, file_size_bytes: number | null, content_type: string | null, world_version_id: WorldVersionId | null, scene_version_id: SceneVersionId | null, created_at: string, updated_at: string, };
