// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StaleReason } from "./StaleReason";
import type { TargetHealth } from "./TargetHealth";

/**
 * A single capture target with its health status
 */
export type CaptureTargetHealth = { shader_id: string, shader_name: string, shader_slug: string, shader_version_id: string, version: string, scene_id: string, scene_name: string, scene_slug: string, profile: string | null, status: TargetHealth, stale_reason: StaleReason | null, last_capture_at: string | null, failure_count: number, };
