// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Freshness status of a capture relative to current versions and newer captures
 */
export type CaptureFreshness = "fresh" | "stale" | "superseded";
