// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneId } from "./SceneId";
import type { ShaderId } from "./ShaderId";
import type { ShaderVersionId } from "./ShaderVersionId";
import type { StaleReason } from "./StaleReason";
import type { TargetHealth } from "./TargetHealth";

/**
 * A single capture target with its health status
 */
export type CaptureTargetHealth = { shader_id: ShaderId, shader_name: string, shader_slug: string, shader_version_id: ShaderVersionId, version: string, scene_id: SceneId, scene_name: string, scene_slug: string, profile?: string, status: TargetHealth, stale_reason?: StaleReason, last_capture_at?: string, failure_count: number, };
