// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary counts for the capture health matrix
 */
export type CaptureHealthSummary = { total_targets: number, completed: number, missing: number, stale: number, failed: number, };
