// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureRunId } from "./CaptureRunId";
import type { CaptureRunStatus } from "./CaptureRunStatus";

export type CaptureRun = { id: CaptureRunId, agent_id?: string, started_at: string, completed_at?: string, status: CaptureRunStatus, total_items: number, completed_items: number, failed_items: number, skipped_items: number, resolution_width: number, resolution_height: number, image_format: string, metadata_json?: Record<string, unknown>, };
