// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureRunId } from "./CaptureRunId";
import type { CaptureRunStatus } from "./CaptureRunStatus";

export type CaptureRun = { id: CaptureRunId, agent_id: string | null, started_at: string, completed_at: string | null, status: CaptureRunStatus, total_items: number, completed_items: number, failed_items: number, skipped_items: number, metadata_json: string | null, };
