// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Capture with denormalized shader/version info for API responses
 */
export type CaptureWithContext = { id: string, scene_id: string, shader_slug: string, shader_name: string, shader_version: string, profile: string | null, image_path: string | null, image_url: string | null, thumbhash: string | null, captured_at: string | null, resolution_width: number | null, resolution_height: number | null, file_size_bytes: number | null, run_id: string | null, run_status: string | null, shader_author: string | null, scene_name: string | null, scene_slug: string | null, };
