// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureId } from "./CaptureId";
import type { CaptureRunId } from "./CaptureRunId";
import type { CaptureRunItemStatus } from "./CaptureRunItemStatus";
import type { SceneId } from "./SceneId";
import type { ShaderVersionId } from "./ShaderVersionId";

/**
 * Capture run item with denormalized shader/scene info for API responses
 */
export type CaptureRunItemWithContext = { id: string, run_id: CaptureRunId, shader_version_id: ShaderVersionId, scene_id: SceneId, profile: string | null, status: CaptureRunItemStatus, capture_id: CaptureId | null, error_message: string | null, error_log: string | null, duration_ms: number | null, started_at: string | null, completed_at: string | null, shader_name: string, shader_slug: string, shader_version: string, scene_name: string, };
