// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureFreshness } from "./CaptureFreshness";
import type { CaptureId } from "./CaptureId";
import type { CaptureRunId } from "./CaptureRunId";
import type { CaptureRunStatus } from "./CaptureRunStatus";
import type { SceneId } from "./SceneId";

/**
 * Capture with denormalized shader/version info for API responses
 */
export type CaptureWithContext = { id: CaptureId, scene_id: SceneId, shader_slug: string, shader_name: string, shader_version: string, profile: string | null, image_path: string | null, image_url: string | null, thumbhash: string | null, captured_at: string | null, resolution_width: number | null, resolution_height: number | null, file_size_bytes: number | null, run_id: CaptureRunId | null, run_status: CaptureRunStatus | null, shader_author: string | null, scene_name: string | null, scene_slug: string | null, freshness: CaptureFreshness, };
