// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureFreshness } from "./CaptureFreshness";
import type { CaptureId } from "./CaptureId";
import type { CaptureRunId } from "./CaptureRunId";
import type { CaptureRunStatus } from "./CaptureRunStatus";
import type { CaptureStatus } from "./CaptureStatus";
import type { CaptureWithContext } from "./CaptureWithContext";
import type { SceneId } from "./SceneId";
import type { ScenePresetId } from "./ScenePresetId";
import type { SceneVersionId } from "./SceneVersionId";
import type { ShaderVersionId } from "./ShaderVersionId";
import type { ShaderVersionProfileId } from "./ShaderVersionProfileId";

/**
 * Full capture details for admin detail view, including technical metadata
 * and related captures for cross-referencing.
 */
export type CaptureDetail = { shader_version_id: ShaderVersionId, status: CaptureStatus, error_message?: string, video_url?: string, avg_fps?: number, min_fps?: number, max_fps?: number, frame_time_avg?: number, frame_time_p99?: number, minecraft_version?: string, iris_version?: string, gpu_model?: string, content_type?: string, scene_version_id?: SceneVersionId, created_at: string, updated_at: string, same_shader_scene: Array<CaptureWithContext>, same_scene: Array<CaptureWithContext>, same_run: Array<CaptureWithContext>, id: CaptureId, scene_id: SceneId, shader_slug: string, shader_name: string, shader_version: string, profile_id?: ShaderVersionProfileId, 
/**
 * Internal profile identifier (e.g. "HIGH", "ULTRA")
 */
profile_name?: string, 
/**
 * Human-readable profile name (e.g. "High", "Ultra")
 */
profile_display_name?: string, image_path: string, thumbhash?: string, captured_at?: string, resolution_width?: number, resolution_height?: number, file_size_bytes?: number, run_id?: CaptureRunId, run_status?: CaptureRunStatus, shader_author?: string, scene_name?: string, scene_slug?: string, preset_id?: ScenePresetId, preset_name?: string, preset_slug?: string, freshness: CaptureFreshness, };
