// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CaptureRun = { id: string, agent_id: string | null, started_at: string, completed_at: string | null, status: string, total_items: number, completed_items: number, failed_items: number, skipped_items: number, metadata_json: string | null, };
