// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shader style category (realistic, fantasy, cartoon, etc.)
 */
export type Category = { id: number, slug: string, name: string, description?: string, };
