// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CleanupKeyStatus } from "./CleanupKeyStatus";

/**
 * Result of a single key deletion attempt
 */
export type CleanupKeyResult = { key: string, status: CleanupKeyStatus, 
/**
 * Reason if skipped
 */
reason: string | null, };
