// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneId } from "./SceneId";
import type { ScenePresetId } from "./ScenePresetId";
import type { SceneVersionId } from "./SceneVersionId";

/**
 * Response from upload confirmation.
 */
export type CompleteUploadResponse = { scene_id: SceneId, scene_version_id: SceneVersionId, preset_id?: ScenePresetId, };
