// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to complete an upload (world creation or version)
 */
export type CompleteUploadRequest = { upload_id: string, };
