// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for confirming a background upload.
 */
export type ConfirmBackgroundUploadRequest = { thumbhash: string | null, width: number | null, height: number | null, file_size_bytes: number | null, content_type: string | null, };
