// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to initiate a new version upload for an existing world
 */
export type CreateWorldVersionUploadRequest = { 
/**
 * SHA256 hash with algorithm prefix (e.g., "sha256:abc123...")
 */
file_hash: string, file_size_bytes: number, };
