// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from POST /api/device/authorize
 */
export type DeviceAuthResponse = { 
/**
 * Secret code for mod to poll with
 */
device_code: string, 
/**
 * User-facing code to enter in browser (GLINT-XXXXXX)
 */
user_code: string, 
/**
 * Base URL for user to visit
 */
verification_uri: string, 
/**
 * Complete URL with code pre-filled
 */
verification_uri_complete: string, 
/**
 * Seconds until this code expires
 */
expires_in: number, 
/**
 * Recommended polling interval in seconds
 */
interval: number, };
