// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A dominant color extracted via mean-shift clustering in CIELAB space.
 */
export type DominantColor = { hex: string, 
/**
 * CIELAB coordinates [L, a, b].
 */
lab: Array<number>, 
/**
 * Proportion of pixels belonging to this cluster.
 */
weight: number, };
