// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Extraction pipeline status for a shader version
 */
export type ExtractionStatus = "pending" | "completed" | "failed" | "skipped";
