// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregate extraction status counts for a shader's versions
 */
export type ExtractionSummary = { completed: number, failed: number, pending: number, skipped: number, total: number, };
