// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One side of a featured comparison pair (shader + capture context).
 */
export type FeaturedSide = { image_path: string, thumbhash?: string, shader_name: string, shader_slug: string, shader_author?: string, shader_version: string, scene_name: string, };
