// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shader technical feature (volumetric, PBR, ray tracing, etc.)
 */
export type Feature = { id: number, slug: string, name: string, description?: string, };
