// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeaturedSide } from "./FeaturedSide";

/**
 * A before/after pair for the homepage hero slider.
 * Dynamically selected from popular shaders.
 */
export type FeaturedPair = { left: FeaturedSide, right: FeaturedSide, };
