// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Job = {
	id: string;
	shader_version_id: string;
	scene_ids: string | null;
	profiles: string | null;
	priority: number;
	status: string;
	attempts: number;
	max_attempts: number;
	agent_id: string | null;
	claimed_at: string | null;
	last_heartbeat: string | null;
	started_at: string | null;
	completed_at: string | null;
	error_message: string | null;
	created_at: string;
};
