// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Luminance statistics: mean value and 8-bin histogram of relative luminance.
 */
export type LuminanceData = { mean: number, 
/**
 * 8 equal-width bins (0.0–0.125, …, 0.875–1.0), normalized to proportions.
 */
histogram: Array<number>, };
