// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureWithContext } from "./CaptureWithContext";

/**
 * Paginated captures response envelope
 */
export type PaginatedCaptures = { items: Array<CaptureWithContext>, total_count: number, page: number, page_size: number, };
