// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Generic paginated response envelope.
 *
 * Used by all list endpoints that support pagination. The TypeScript binding
 * is generated as a generic `Paginated<T>` so frontend code can use
 * `Paginated<CaptureListItem>`, `Paginated<ShaderListItem>`, etc.
 */
export type Paginated<T> = { items: Array<T>, total: number, page: number, page_size: number, };
