// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User roles with compile-time safety.
 *
 * Stored as lowercase text in PostgreSQL (`user`, `admin`, `agent`).
 * Using an enum prevents typo-based auth bypasses that string comparisons allow.
 */
export type Role = "user" | "admin" | "agent";
