// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneId } from "./SceneId";
import type { SceneVersionId } from "./SceneVersionId";

/**
 * A specific revision of a Scene's config (position, camera, weather, etc.)
 */
export type SceneVersion = { id: SceneVersionId, scene_id: SceneId, x: number, y: number, z: number, pitch: number, yaw: number, time_of_day_ticks: number, weather: string, weather_intensity: number, moon_phase: number | null, biome: string | null, created_at: string, };
