// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneId } from "./SceneId";
import type { SceneVersion } from "./SceneVersion";
import type { WorldId } from "./WorldId";

export type SceneWithWorld = { version: SceneVersion, world_name?: string, world_slug?: string, image_url?: string, thumbhash?: string, capture_count: number, id: SceneId, name: string, slug: string, description?: string, world_id: WorldId, dimension: string, parent_scene_id?: string, active: boolean, created_at: string, };
