// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneId } from "./SceneId";
import type { ScenePresetId } from "./ScenePresetId";

/**
 * A preset within a scene (time/weather/moon_phase variation)
 */
export type ScenePreset = { id: ScenePresetId, scene_id: SceneId, name: string, slug: string, time_of_day_ticks: number, weather: string, weather_intensity: number, moon_phase?: number, sort_order: number, created_at: string, updated_at: string, };
