// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneId } from "./SceneId";
import type { WorldId } from "./WorldId";

export type Scene = { id: SceneId, name: string, slug: string, description?: string, world_id: WorldId, dimension: string, parent_scene_id?: string, active: boolean, created_at: string, };
