// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneId } from "./SceneId";
import type { SceneVersion } from "./SceneVersion";
import type { WorldId } from "./WorldId";

/**
 * Scene with its latest version nested (for API responses that need config)
 */
export type SceneWithVersion = { version: SceneVersion, id: SceneId, name: string, slug: string, description: string | null, world_id: WorldId, dimension: string, parent_scene_id: string | null, active: boolean, created_at: string, };
