// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureWithContext } from "./CaptureWithContext";
import type { SceneId } from "./SceneId";
import type { SceneVersion } from "./SceneVersion";
import type { World } from "./World";
import type { WorldId } from "./WorldId";

export type SceneWithCaptures = { version: SceneVersion, world?: World, captures: Array<CaptureWithContext>, id: SceneId, name: string, slug: string, description?: string, world_id: WorldId, dimension: string, parent_scene_id?: string, active: boolean, created_at: string, };
