// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneVersion } from "./SceneVersion";

export type SceneWithWorld = { version: SceneVersion, world_name: string | null, world_slug: string | null, image_url: string | null, thumbhash: string | null, capture_count: number, id: string, name: string, slug: string, description: string | null, world_id: string, dimension: string, parent_scene_id: string | null, active: boolean, created_at: string, };
