// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneId } from "./SceneId";
import type { SceneVersion } from "./SceneVersion";

export type SceneListAdmin = { version: SceneVersion, image_path?: string, thumbhash?: string, capture_count: number, id: SceneId, name: string, slug: string, description?: string, dimension: string, active: boolean, created_at: string, };
