// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureWithContext } from "./CaptureWithContext";
import type { SceneId } from "./SceneId";
import type { ScenePreset } from "./ScenePreset";
import type { SceneVersion } from "./SceneVersion";

export type SceneWithCaptures = { version: SceneVersion, presets: Array<ScenePreset>, captures: Array<CaptureWithContext>, id: SceneId, name: string, slug: string, description?: string, dimension: string, active: boolean, created_at: string, };
