// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneVersion } from "./SceneVersion";
import type { Tag } from "./Tag";

export type SceneListItem = { version: SceneVersion, tags: Array<Tag>, image_url: string | null, thumbhash: string | null, capture_count: number, id: string, name: string, slug: string, description: string | null, world_id: string, dimension: string, parent_scene_id: string | null, active: boolean, created_at: string, };
