// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneId } from "./SceneId";
import type { SceneVersion } from "./SceneVersion";
import type { Tag } from "./Tag";

export type SceneListItem = { version: SceneVersion, tags: Array<Tag>, image_url?: string, thumbhash?: string, capture_count: number, id: SceneId, name: string, slug: string, description?: string, dimension: string, active: boolean, created_at: string, };
