// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionInfo = { token_prefix: string, 
/**
 * How the session was created: "web" (browser OAuth) or "device" (mod)
 */
source: string, 
/**
 * Whether this is the session making the current request
 */
is_current: boolean, created_at: string, expires_at: string, };
