// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShaderAdopted } from "./ShaderAdopted";

export type ShaderSearchResult = { platform: string, platform_id: string, slug: string, name: string, description: string, icon_url?: string, author: string, downloads: number, categories: Array<string>, platform_url: string, 
/**
 * When the shader was last updated on its platform
 */
updated_at?: string, 
/**
 * Present when this shader has already been adopted into Glint
 */
adopted?: ShaderAdopted, };
