// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureWithContext } from "./CaptureWithContext";
import type { ShaderVersion } from "./ShaderVersion";

export type ShaderWithCaptures = { versions: Array<ShaderVersion>, captures: Array<CaptureWithContext>, id: string, name: string, slug: string, description: string | null, modrinth_id: string | null, curseforge_id: string | null, website_url: string | null, created_at: string, updated_at: string, };
