// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtractionStatus } from "./ExtractionStatus";
import type { ShaderId } from "./ShaderId";
import type { ShaderVersionId } from "./ShaderVersionId";

/**
 * Specific release of a shader pack
 */
export type ShaderVersion = { id: ShaderVersionId, shader_id: ShaderId, version: string, modrinth_version_id?: string, curseforge_file_id?: number, download_url?: string, file_hash?: string, file_size?: number, game_versions?: Array<string>, release_channel?: string, upstream_published_at?: string, created_at: string, capture_failure_count: number, last_capture_error?: string, extraction_status: ExtractionStatus, extraction_error?: string, extracted_at?: string, };
