// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShaderId } from "./ShaderId";

/**
 * Reference to an already-adopted shader in Glint
 */
export type ShaderAdopted = { id: ShaderId, slug: string, };
