// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShaderId } from "./ShaderId";
import type { ShaderVersion } from "./ShaderVersion";

export type ShaderWithVersions = { versions: Array<ShaderVersion>, id: ShaderId, name: string, slug: string, description?: string, modrinth_id?: string, curseforge_id?: string, website_url?: string, icon_url?: string, source_url?: string, license_id?: string, upstream_downloads?: number, upstream_updated_at?: string, last_synced_at?: string, created_at: string, updated_at: string, view_count: number, preferred_version_id?: string, capture_enabled: boolean, deleted_at?: string, };
