// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShaderSearchResult } from "./ShaderSearchResult";

export type ShaderSearchResponse = { results: Array<ShaderSearchResult>, total_modrinth: number, total_curseforge?: number, };
