// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShaderVersionId } from "./ShaderVersionId";

/**
 * Extracted metadata sidecar for a shader version (1:1 relationship)
 */
export type ShaderVersionMetadata = { shader_version_id: ShaderVersionId, pipeline_features?: Record<string, unknown>, iris_features_required?: Array<string>, iris_features_optional?: Array<string>, settings_screen?: Array<Record<string, unknown>>, file_paths?: Array<string>, dimension_support?: Array<string>, has_custom_textures?: boolean, extracted_at: string, };
