// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shader pack identity (not version-specific)
 */
export type Shader = { id: string, name: string, slug: string, description: string | null, modrinth_id: string | null, curseforge_id: string | null, website_url: string | null, created_at: string, updated_at: string, };
