// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Specific release of a shader pack
 */
export type ShaderVersion = {
	id: string;
	shader_id: string;
	version: string;
	modrinth_version_id: string | null;
	download_url: string | null;
	file_hash: string | null;
	/**
	 * JSON array of profile names, discovered after first capture
	 */
	supported_profiles: string | null;
	created_at: string;
};
