// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShaderId } from "./ShaderId";
import type { ShaderVersionId } from "./ShaderVersionId";

/**
 * ShaderVersion enriched with capture count for detail endpoints
 */
export type ShaderVersionDetail = { capture_count: number, id: ShaderVersionId, shader_id: ShaderId, version: string, modrinth_version_id?: string, curseforge_file_id?: number, download_url?: string, file_hash?: string, file_size?: number, game_versions?: Array<string>, release_channel?: string, 
/**
 * Array of profile names, discovered after first capture
 */
supported_profiles?: Array<string>, upstream_published_at?: string, created_at: string, capture_failure_count: number, last_capture_error?: string, };
