// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShaderSearchResult = { platform: string, platform_id: string, slug: string, name: string, description: string, icon_url: string | null, author: string, downloads: number, categories: Array<string>, platform_url: string, };
