// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShaderId } from "./ShaderId";
import type { ShaderVersionId } from "./ShaderVersionId";

/**
 * ShaderVersion enriched with capture count for detail endpoints
 */
export type ShaderVersionDetail = { capture_count: number, id: ShaderVersionId, shader_id: ShaderId, version: string, modrinth_version_id: string | null, curseforge_file_id: number | null, download_url: string | null, file_hash: string | null, file_size: number | null, game_versions: Array<string> | null, release_channel: string | null, 
/**
 * Array of profile names, discovered after first capture
 */
supported_profiles: Array<string> | null, upstream_published_at: string | null, created_at: string, capture_failure_count: number, last_capture_error: string | null, };
