// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShaderId } from "./ShaderId";

/**
 * Shader author from upstream platform
 */
export type ShaderAuthor = { id: string, shader_id: ShaderId, name: string, url: string | null, platform: string, };
