// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a capture target is stale (only present when status == Stale)
 */
export type StaleReason = "scene_updated" | "preset_edited";
