// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight aggregate statistics for the index page.
 */
export type Stats = { shader_count: number, scene_count: number, capture_count: number, user_count: number, run_count: number, latest_capture_at?: string, };
