// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StorageBucket = { date: number, cumulative_bytes: number, cumulative_count: number, bucket_bytes: number, };
