// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StorageStats = { total_bytes: number, capture_count: number, avg_bytes: number, missing_count: number, };
