// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditObject } from "./AuditObject";
import type { AuditReference } from "./AuditReference";
import type { AuditSummary } from "./AuditSummary";

/**
 * Full audit result returned by POST /api/admin/storage/audit
 */
export type StorageAuditResult = { 
/**
 * Objects in R2 with no matching DB row
 */
orphaned: Array<AuditObject>, 
/**
 * Objects under _uploads/ with no pending_uploads record
 */
stale_staging: Array<AuditObject>, 
/**
 * DB rows referencing R2 URLs where the object doesn't exist in R2
 */
missing: Array<AuditReference>, 
/**
 * Objects under unrecognized prefixes
 */
unknown_prefix: Array<AuditObject>, 
/**
 * DB rows where stored URL doesn't match what would be generated from the key
 */
url_mismatches: Array<AuditReference>, 
/**
 * Summary statistics
 */
summary: AuditSummary, };
