// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for POST /api/admin/storage/cleanup
 */
export type StorageCleanupRequest = { 
/**
 * R2 keys to delete (max 200)
 */
keys: Array<string>, };
