// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CleanupKeyResult } from "./CleanupKeyResult";

/**
 * Response from POST /api/admin/storage/cleanup
 */
export type StorageCleanupResult = { results: Array<CleanupKeyResult>, deleted_count: number, skipped_count: number, failed_count: number, freed_bytes: number, };
