// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Scene tag (indoor, sunset, water, etc.)
 */
export type Tag = { id: number, slug: string, name: string, description: string | null, };
