// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShaderId } from "./ShaderId";

/**
 * A shader that is currently trending (high view count in a recent time window).
 * The `view_count` from the flattened `Shader` represents the all-time total;
 * `trending_views` is the count within the requested time window.
 */
export type TrendingShader = { trending_views: number, image_url: string | null, thumbhash: string | null, id: ShaderId, name: string, slug: string, description: string | null, modrinth_id: string | null, curseforge_id: string | null, website_url: string | null, icon_url: string | null, source_url: string | null, license_id: string | null, upstream_downloads: number | null, upstream_updated_at: string | null, last_synced_at: string | null, created_at: string, updated_at: string, view_count: number, };
