// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThemeMode } from "./ThemeMode";

/**
 * Request body for updating background metadata.
 */
export type UpdateBackgroundRequest = { enabled: boolean | null, theme_mode: ThemeMode | null, sort_order: number | null, };
