// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateShaderRequest = { name?: string, slug?: string, description?: string, modrinth_id?: string, curseforge_id?: string, website_url?: string, 
/**
 * Set to a version ID to pin, empty string to clear, omit to leave unchanged.
 */
preferred_version_id?: string, capture_enabled?: boolean, };
