// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PendingSceneUploadId } from "./PendingSceneUploadId";

/**
 * Response from upload initiation endpoints.
 */
export type UploadInitiatedResponse = { upload_id: PendingSceneUploadId, upload_url: string, };
