// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneId } from "./SceneId";
import type { SceneVersionId } from "./SceneVersionId";

export type WorkScene = { id: SceneId, slug: string, name: string, dimension: string, x: number, y: number, z: number, yaw: number, pitch: number, time_of_day_ticks: number, weather: string, weather_intensity: number, moon_phase?: number, biome?: string, fov: number, render_distance: number, minecraft_version?: string, version_id?: SceneVersionId, };
