// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScenePresetId } from "./ScenePresetId";

export type WorkPreset = { id: ScenePresetId, name: string, slug: string, time_of_day_ticks?: number, weather?: string, weather_intensity?: number, moon_phase?: number, };
