// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneId } from "./SceneId";
import type { ScenePresetId } from "./ScenePresetId";
import type { SceneVersionId } from "./SceneVersionId";
import type { ShaderId } from "./ShaderId";
import type { ShaderVersionId } from "./ShaderVersionId";
import type { ShaderVersionProfileId } from "./ShaderVersionProfileId";

/**
 * A single work item: one (shader_version, scene, preset, profile) tuple to capture
 */
export type WorkItem = { shader_version_id: ShaderVersionId, shader_id: ShaderId, shader_slug: string, shader_name: string, version: string, download_url?: string, file_hash?: string, scene_id: SceneId, scene_slug: string, scene_name: string, scene_dimension: string, scene_x: number, scene_y: number, scene_z: number, scene_yaw: number, scene_pitch: number, scene_time_of_day_ticks: number, scene_weather: string, scene_weather_intensity: number, scene_moon_phase?: number, scene_biome?: string, preset_id?: ScenePresetId, preset_name?: string, preset_slug?: string, preset_time_of_day_ticks?: number, preset_weather?: string, preset_weather_intensity?: number, preset_moon_phase?: number, package_url?: string, package_hash?: string, package_size_bytes?: number, scene_minecraft_version?: string, scene_fov: number, scene_render_distance: number, scene_version_id?: SceneVersionId, profile_id?: ShaderVersionProfileId, profile_name?: string, };
