// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single work item: one (shader_version, scene, profile) triple to capture
 */
export type WorkItem = { shaderVersionId: string, shaderId: string, shaderSlug: string, shaderName: string, version: string, downloadUrl: string | null, fileHash: string | null, sceneId: string, sceneSlug: string, sceneName: string, sceneDefinitionJson: string, worldId: string, worldSlug: string, worldName: string, worldFileUrl: string | null, worldFileHash: string | null, worldSizeBytes: number | null, profile: string | null, };
