// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorldId } from "./WorldId";
import type { WorldPreviewCapture } from "./WorldPreviewCapture";
import type { WorldVersion } from "./WorldVersion";

/**
 * World summary for list endpoints with aggregate counts
 */
export type WorldListItem = { latest_version?: WorldVersion, scene_count: number, version_count: number, capture_count: number, preview?: WorldPreviewCapture, id: WorldId, slug: string, name: string, description?: string, minecraft_version: string, created_at: string, updated_at: string, };
