// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorldId } from "./WorldId";

/**
 * Downloadable world files containing scenes
 */
export type World = { id: WorldId, slug: string, name: string, description?: string, minecraft_version: string, created_at: string, updated_at: string, };
