// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorldId } from "./WorldId";
import type { WorldVersionId } from "./WorldVersionId";

/**
 * A specific revision of a World's save file
 */
export type WorldVersion = { id: WorldVersionId, world_id: WorldId, file_url?: string, file_hash?: string, size_bytes?: number, created_at: string, };
