// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A specific revision of a World's save file
 */
export type WorldVersion = { id: string, world_id: string, file_url: string | null, file_hash: string | null, size_bytes: number | null, created_at: string, };
