// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scene } from "./Scene";
import type { WorldId } from "./WorldId";
import type { WorldVersion } from "./WorldVersion";

/**
 * World with its associated scenes and latest version
 */
export type WorldWithDetails = { scenes: Array<Scene>, latest_version: WorldVersion | null, id: WorldId, slug: string, name: string, description: string | null, minecraft_version: string, created_at: string, updated_at: string, };
