// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scene } from "./Scene";

/**
 * World with its associated scenes
 */
export type WorldWithScenes = { scenes: Array<Scene>, id: string, slug: string, name: string, description: string | null, minecraft_version: string, file_url: string | null, file_hash: string | null, size_bytes: number | null, created_at: string, updated_at: string, };
