// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorldVersion } from "./WorldVersion";

/**
 * World summary for list endpoints (no scenes loaded)
 */
export type WorldListItem = { latest_version: WorldVersion | null, id: string, slug: string, name: string, description: string | null, minecraft_version: string, created_at: string, updated_at: string, };
