// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorldPreviewCapture } from "./WorldPreviewCapture";
import type { WorldVersion } from "./WorldVersion";

/**
 * World summary for list endpoints with aggregate counts
 */
export type WorldListItem = { latest_version: WorldVersion | null, scene_count: number, version_count: number, capture_count: number, preview: WorldPreviewCapture | null, id: string, slug: string, name: string, description: string | null, minecraft_version: string, created_at: string, updated_at: string, };
