plugins {
    id 'org.jetbrains.kotlin.jvm'
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    common
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

loom {
    neoForge {}
}

dependencies {
    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }

    neoForge libs.neoforge

    modImplementation libs.architectury.neoforge
    
    modImplementation libs.kotlin.stdlib
    modImplementation libs.kotlinx.coroutines.core
    modImplementation libs.kotlinx.serialization.core
    modImplementation libs.kotlinx.serialization.json
    
    implementation libs.webp.imageio

    developmentNeoForge libs.kotlin.stdlib

    include libs.kotlin.stdlib
    include libs.kotlinx.coroutines.core
    include libs.kotlinx.serialization.core
    include libs.kotlinx.serialization.json
    include libs.webp.imageio

    // owo-lib UI framework
    api libs.owo.neoforge
    annotationProcessor libs.owo.neoforge
    include libs.owo.neoforge
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand 'version': project.version
    }
}
