/**
 * Generate optimized WebP wallpapers and thumbhash placeholders from source JPEGs.
 *
 * For each curated wallpaper index:
 * - Resizes to 480px wide, converts to WebP quality 50
 * - Generates a thumbhash for instant placeholder display
 * - Writes a typed manifest to frontend/src/lib/data/wallpaper-manifest.ts
 *
 * Usage: bun scripts/optimize-wallpapers.ts [--all]
 */

import { existsSync, mkdirSync, readdirSync } from 'fs';
import sharp from 'sharp';
import { rgbaToThumbHash } from 'thumbhash';
import { c, elapsed } from './lib/fmt';
import { runPiped } from './lib/proc';

const WALLPAPERS_DIR = 'frontend/static/wallpapers';
const OPTIMIZED_DIR = `${WALLPAPERS_DIR}/optimized`;
const MANIFEST_PATH = 'frontend/src/lib/data/wallpaper-manifest.ts';

// Curated wallpaper indices used in +layout.svelte
const CURATED_INDICES = [...new Set([13, 53, 31, 71, 18, 65, 32, 97, 102, 69, 23, 94])];

const all = process.argv.includes('--all');

let indices: number[];
if (all) {
	const files = readdirSync(WALLPAPERS_DIR).filter((f) => /^\d+\.jpg$/i.test(f));
	indices = files.map((f) => parseInt(f)).sort((a, b) => a - b);
} else {
	indices = CURATED_INDICES;
}

const start = Date.now();
mkdirSync(OPTIMIZED_DIR, { recursive: true });

// Ensure the manifest directory exists
const manifestDir = MANIFEST_PATH.replace(/\/[^/]+$/, '');
mkdirSync(manifestDir, { recursive: true });

interface ManifestEntry {
	optimized: string;
	thumbhash: string;
}

const manifest: Record<number, ManifestEntry> = {};
let processed = 0;
let skipped = 0;

for (const index of indices) {
	const src = `${WALLPAPERS_DIR}/${index}.jpg`;
	if (!existsSync(src)) {
		console.warn(c('33', `⚠ Skipping ${index}: ${src} not found`));
		skipped++;
		continue;
	}

	const dest = `${OPTIMIZED_DIR}/${index}.webp`;

	// Resize to 480px wide, WebP quality 50
	await sharp(src).resize(480).webp({ quality: 50 }).toFile(dest);

	// Generate thumbhash: resize to ≤100px, extract raw RGBA
	const thumbImage = sharp(src).resize(100, 100, { fit: 'inside' }).ensureAlpha();
	const { data, info } = await thumbImage.raw().toBuffer({ resolveWithObject: true });
	const hash = rgbaToThumbHash(info.width, info.height, data);
	const thumbhash = Buffer.from(hash).toString('base64');

	manifest[index] = {
		optimized: `/wallpapers/optimized/${index}.webp`,
		thumbhash,
	};
	processed++;
}

// Write typed manifest
const entries = Object.entries(manifest)
	.sort(([a], [b]) => Number(a) - Number(b))
	.map(([idx, entry]) => {
		return `\t${idx}: { optimized: ${JSON.stringify(entry.optimized)}, thumbhash: ${JSON.stringify(entry.thumbhash)} },`;
	})
	.join('\n');

const manifestContent = `// Auto-generated by scripts/optimize-wallpapers.ts — do not edit
export const wallpaperManifest: Record<number, { optimized: string; thumbhash: string }> = {
${entries}
};
`;

await Bun.write(MANIFEST_PATH, manifestContent);

// Format the generated manifest
runPiped(['bun', 'run', '--cwd', 'frontend', 'format', 'src/lib/data/']);

const msg = `${processed} image${processed !== 1 ? 's' : ''}`;
const skipMsg = skipped > 0 ? `, ${skipped} skipped` : '';
console.log(c('32', `✓ wallpapers`) + ` (${elapsed(start)}s, ${msg}${skipMsg})`);
